'use client'
import "@/styles/main.scss"
import type {Metadata} from 'next'
import {Poppins} from 'next/font/google'
import React from "react";
import {persistStore} from "@/features/auth/logic/persist.store";
import {authStore} from "@/features/auth/logic/auth.store";

const poppins = Poppins({subsets: ["latin"], weight: ["400", "500", '600', '700', '800']});

// export const metadata: Metadata = {
//   title: 'Pro Manage',
//   description: 'Generated by create next app',
// }

persistStore(authStore, 'AUTH');

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body className={poppins.className}>{children}</body>
    </html>
  )
}
